### ISSUE TITLE
Installation fails due to unrecognized archive format

### ISSUE THREAD

**Issue by alexruf** [asdf-community/asdf-cue#10]
Installation of cue versions > 0.2.2 fail with the following error:

```bash
> asdf install cue latest
∗ Downloading and installing cue...
tar: Error opening archive: Unrecognized archive format
\e[31mFail:\e[m Could not uncompress
\e[31mFail:\e[m An error occurred
```

Not sure why this is the case.

**Comment by smorimoto** [comment]
Fixed in #15.

**Comment by jritsema** [comment]
I'm also getting this error on macos arm64 (m1)
```
asdf install cue latest
∗ Downloading and installing cue 0.4.0...
tar: Error opening archive: Unrecognized archive format
\e[31mFail:\e[m Could not uncompress
\e[31mFail:\e[m An error occurred
```

Am I doing something wrong?

**Comment by smorimoto** [comment]
It seems that there is no pre-built release for Apple Silicon (upstream side).

**Comment by spencergilbert** [comment]
> I'm also getting this error on macos arm64 (m1)
> ```
> asdf install cue latest
> ∗ Downloading and installing cue 0.4.0...
> tar: Error opening archive: Unrecognized archive format
> \e[31mFail:\e[m Could not uncompress
> \e[31mFail:\e[m An error occurred
> ```
> 
> Am I doing something wrong?

I think cue doesn't create Mac ARM artifacts. Would you mind opening an issue and we can see if we can use the x86 binary with Rosetta instead?

**Comment by jritsema** [comment]
Ah yes that does make sense. I will create an issue. Btw, I was able to install it via homebrew which installs the x86 binary, so it does seem to work via Rosetta. Thanks!

**Comment by NeoHsu** [comment]
Maybe we can assign MacOS always use amd64 binary to fix this issue?
