### ISSUE TITLE
Downloads broken for latest releases

### ISSUE THREAD

**Issue by taharah** [asdf-community/asdf-cue#9]
CUE has changed the name format of the release artifacts for the latest releases. It looks like starting with v0.3.0-beta.5, the naming scheme changed from:

```
https://github.com/cuelang/cue/releases/download/v0.3.0-beta.5/cue_0.3.0-beta.5_Linux_x86_64.tar.gz
```

to...

```
https://github.com/cuelang/cue/releases/download/v0.3.0-beta.7/cue_v0.3.0-beta.7_linux_amd64.tar.gz
```

**Comment by smorimoto** [comment]
Let me check that.

**Comment by smorimoto** [comment]
Fixed by https://github.com/asdf-community/asdf-cue/commit/58f2629da133b5d9c6ae49bf884011ad32387dd1.

**Comment by taharah** [comment]
@smorimoto thank you for the quick response and fix! I was working on throwing together something myself, but you beat me to it 😄
